
version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - "./src:/usr/app/src"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"